version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./exampledb:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=afroraydude-site"
      - "MYSQL_USER=afroraydude-site"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
  composer:
    restart: 'no'
    image: library/composer
    command: install
    volumes:
      - ./slim-skeleton:/app
  app:
    build: 
      context: ./
      dockerfile: app.dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./slim-skeleton:/var/www/html
    depends_on:
      - db
      - composer
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./slim-skeleton:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
