version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./exampledb:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=afroraydude-site"
      - "MYSQL_USER=afroraydude-site"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
  composer:
      restart: 'no'
      image: library/composer
      command: require slim/slim "^3.0"
      volumes:
        - ./slim-skeleton:/var/www
  app:
      build: .
      working_dir: /var/www
      ports:
          - "8000:80"
      volumes:
          - ./slim-skeleton:/var/www
      depends_on:
          - db
          - composer
